
[mobs]
	hidden_levels = []
	blacklist = ["minecraft:horse", "cnb:friendly_sporeling", "minecraft:dolphin", "alexsmobs:fly", "projectvibrantjourneys:night_bat", "minecraft:villager"]
	whitelist = ["goblinsanddungeons:gob", "goblinsanddungeons:garch", "alexsmobs:guster", "iceandfire:dread_ghoul", "iceandfire:dread_thrall", "quark:forgotten", "mutantbeasts:mutant_skeleton", "minecraft:spider", "legendarycreatures:corpse_eater", "legendarycreatures:scarecrow", "minecraft:enderman", "minecraft:husk", "aquamirae:anglerfish", "alexsmobs:kangaroo", "alexsmobs:emu", "minecraft:stray", "iceandfire:siren", "guardvillagers:guard", "goblinsanddungeons:goom", "goblinsanddungeons:gobber", "goblinsanddungeons:goblin_king", "goblinsanddungeons:hobgob", "minecraft:polar_bear", "iceandfire:gorgon", "minecraft:skeleton", "mutantbeasts:mutant_zombie", "minecraft:creeper", "eidolon:zombie_brute", "minecraft:witch", "earthmobsmod:lobber_zombie", "eidolon:wraith", "quark:wrapped", "graveyard:acolyte", "mowziesmobs:barakoaya", "mowziesmobs:barako", "legendarycreatures:desert_mojo", "legendarycreatures:forest_mojo", "legendarycreatures:hound", "legendarycreatures:scorpion", "legendarycreatures:scorpion_baby", "legendarycreatures:peacock_spider", "legendarycreatures:bullfrog", "goblinsanddungeons:ogre", "iceandfire:cockatrice", "mowziesmobs:ferrous_wroughtnaut", "dungeons_mobs:skeleton_vanguard", "ba_bt:silver_skeleton", "cnb:yeti", "earthmobsmod:bouldering_zombie", "minecraft:zombie", "dungeons_mobs:whisperer", "mowziesmobs:foliaath", "minecraft:silverfish", "graveyard:reaper", "minecraft:zombie_villager", "minecraft:pillager", "minecraft:vindicator", "dungeons_mobs:jungle_zombie", "iceandfire:ghost", "alexsmobs:grizzly_bear"]
	always_show_level = false
	show_level_when_looking_at = true
	exp_bonus_per_level = 0.1

[attributes]
	attribute_bonuses = [["minecraft:generic.movement_speed", 0.001], ["minecraft:generic.flying_speed", 0.001], ["minecraft:generic.attack_damage", 0.1], ["minecraft:generic.armor", 0.1], ["minecraft:generic.max_health", 0.05], ["autoleveling:monster.projectile_damage_bonus", 0.1], ["autoleveling:monster.explosion_damage_bonus", 0.1]]

[default_leveling_settings]
	starting_level = 1
	levels_per_day = 0.2
	max_level = 200
	level_power_per_deepness = 0.0
	random_level_bonus = 10
	levels_per_deepness = 0.0
	level_power_per_distance = 0.0
	levels_per_distance = 1.0E-5

