#This config allows you to add or remove folders or single files as Data-/Resourcepacks
#For that simply specify the file path to the folder/file relative to your .minecraft folder
[resourcepacks]
required = [
    "resourcepacks/xali's Enhanced Vanilla v1.11.1.zip",
	"resourcepacks/xali's Potions v1.0.zip",
	"resourcepacks/xali's Enchanted Books v0.12.0.zip",
	"resourcepacks/xalis Enhanced Diamond v0.1.zip",
	"resourcepacks/5better-end-flower.zip",
	"resourcepacks/FrostbiteBrimstone.zip",
	"resourcepacks/MBTR_v1.2.zip",
	"resourcepacks/Lum-5.0-1.19.zip",
	"resourcepacks/PeridotGarden+Seagrass(v1.0).zip",
	"resourcepacks/GrappleRetextured_1.16_v1.zip",
	"resourcepacks/bottled-dye-e620.zip",
	"resourcepacks/better-banners-e1870.zip",
	"resourcepacks/waystones.zip",
	"resourcepacks/better-crops-3d-16x.zip",
	"resourcepacks/Enhanced Dripstone v1.1.zip",
	"resourcepacks/Spartan Retextured.zip",
	"resourcepacks/FreshAnimations_v1.6.zip",
	"resourcepacks/Better+Skeletons+FA.zip",
	"resourcepacks/Better+illagers+FA.zip",
	"resourcepacks/Creeper_Overhaul_RP_1.1.2.zip",
	"resourcepacks/Stardew Valley Chickens.zip",
	"resourcepacks/Visual Titles.zip",
	"resourcepacks/Shiny's+Rats+v1.zip",
	"resourcepacks/OR+-+LegendaryTooltips+v1.3.0.zip",
	"resourcepacks/Legendary_Resource_Pack_1.16.5.zip"
]

[datapacks]
required = [
    "global_data_packs/Desert_village_1.16.X.zip",
	"global_data_packs/ichphilipp-s-endcity-v1-1-1-16-2-forge.zip",
	"global_data_packs/mountain-villagers-reissue-e1110.zip",
	"global_data_packs/New-Pillagers.zip",
	"global_data_packs/villages-overhauled-e900.zip",
	"global_data_packs/woodland_mansion_v2.zip",
	"global_data_packs/Minecraft_Legends_Datapack_1.16.5.zip",
    "global_packs/required_datapacks/"
]

optional = [
    "optional_data_packs/",
    "global_packs/optional_datapacks/"
]