storagenetwork = false
tconstruct = false
fastfurnaceminusreplacement = false
sophisticatedbackpacks = false
fastfurnace = true
craftingstation = false
ironfurnaces = false
occultism = false
jei = true
extendedcrafting = true
fastbenchminusreplacement = false
refinedstorageaddons = false
craftingcraft = false
toms_storage = false
refinedstorage = false
prettypipes = false
fastsuite = true
fastbench = true
cyclic = false
appliedenergistics2 = false

