#Max Monsters (zombie,skeleton, creeper, etc.)
#Range: 1 ~ 210
monsterCap = 50
#MaxCreatures (sheep, cows)
#Range: 1 ~ 210
creatureCap = 80
#Max Ambient (bats)
#Range: 1 ~ 210
ambientCap = 10
#Max water creature (squid, dolphins)
#Range: 1 ~ 210
waterCreatureCap = 5
#Max Water Ambient (Tropical Fish)
#Range: 1 ~ 210
waterAmbientCap = 5
#Max Water Creature (Glow Squid)
#Range: 1 ~ 210
undergroundWaterCreatureCap = 3

