
#List of ranks
[[ranks]]
	effects = []
	defaultColor = 16777215
	chance = 0.05
	tier = 0
	growthFactor = 0
	presetAffixes = []
	numAffixes = 0

[[ranks]]
	effects = []
	defaultColor = 8113484
	chance = 0.1
	tier = 1
	growthFactor = 1
	presetAffixes = []
	numAffixes = 1

[[ranks]]
	effects = []
	defaultColor = 3776767
	chance = 0.2
	tier = 2
	growthFactor = 2
	presetAffixes = []
	numAffixes = 2

[[ranks]]
	effects = []
	defaultColor = 16644928
	chance = 0.3
	tier = 3
	growthFactor = 4
	presetAffixes = []
	numAffixes = 3

[[ranks]]
	effects = []
	defaultColor = 14425887
	chance = 0.3
	tier = 4
	growthFactor = 7
	presetAffixes = []
	numAffixes = 4

