
[triggers]
	[triggers.height]
		level = "60"
		identifier = "height"
		check_above_level = true
	[triggers.universal]
		fade_out = "200"
		persistence = "0"
		trigger_delay = "0"
		song_delay = "1200:1800"
		start_delay = "0"
		fade_in = "100"
	[triggers.menu]

	[[triggers.time]]
		identifier = "day"
		time_bundle = "day"
		priority = "1"
		song_delay = "6000"

	[[triggers.time]]
		identifier = "night"
		time_bundle = "night"
		priority = "1"
		song_delay = "6000"

	[[triggers.dimension]]
		identifier = "overworld"
		resource_name = [ "overworld" ]
		priority = "1"

	[[triggers.dimension]]
		identifier = "nether"
		resource_name = [ "the_nether" ]
		priority = "1"

	[[triggers.dimension]]
		identifier = "end"
		resource_name = [ "the_end" ]
		priority = "1"

	[[triggers.season]]
		identifier = "spring"
		level = "0"
		priority = "1"

	[[triggers.season]]
		identifier = "autumn"
		level = "2"
		priority = "1"

	[[triggers.season]]
		identifier = "summer"
		level = "1"
		priority = "1"

	[[triggers.season]]
		identifier = "winter"
		level = "3"
		priority = "1"

[songs]

	[songs.day_amb1_elders_footsteps]
		triggers = [ "time-day" "height-height" "dimension-overworld" ]
		chance = "150"

	[songs.day_amb2_lovings_season]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "150"

	[songs.day_amb3_wondering_nature]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "150"

	[songs.day1_gilles]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day2_past]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day3_scherzo]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day4_village]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day5_wisdom]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day6_chris]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day7_skyward_sword]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day8_door]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day9_subwoofer]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day10_living]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day11_minecraft]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day12_mice_on_venus]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day13_dry_hands]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day14_wet_hands]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day15_clark]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day16_sweden]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day17_blind_spots]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day18_biome_fest]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day19_haunt_muskie]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day20_aria_math]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day21_taswell]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day22_dreiton]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.day23_danny]
		triggers = [ "time-day" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night_amb1_everyone_s_sleep]
		triggers = [ "height-height" "time-night" "dimension-overworld" ]
		chance = "150"

	[songs.night_amb2_lullaby]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "150"

	[songs.night_amb3_poem_for_the_moon]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "150"

	[songs.night_amb4_key]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "150"

	[songs.night_amb5_oxygene]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "150"

	[songs.night1_dreamy]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night2_following_the_stars]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night3_jardins]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night4_nostalgia]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night5_snowfall]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night6_equinoxe]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night7_ki]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night8_dead_voxel]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night9_floating_trees]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.night10_kyoto]
		triggers = [ "time-night" "dimension-overworld" "height-height" ]
		chance = "75"

	[songs.nether_amb1_lll_omened]
		triggers = [ "dimension-nether" ]
		chance = "150"

	[songs.nether_amb2_laments]
		triggers = [ "dimension-nether" ]
		chance = "150"

	[songs.nether_amb3_stray_ghasts]
		triggers = [ "dimension-nether" ]
		chance = "150"

	[songs.nether1_deep_explore]
		triggers = [ "dimension-nether" ]
		chance = "75"

	[songs.nether2_lonely]
		triggers = [ "dimension-nether" ]
		chance = "75"

	[songs.nether3_piglins_march]
		triggers = [ "dimension-nether" ]
		chance = "75"

	[songs.nether4_portentous]
		triggers = [ "dimension-nether" ]
		chance = "75"

	[songs.nether5_concrete_halls]
		triggers = [ "dimension-nether" ]
		chance = "75"

	[songs.nether6_warmth]
		triggers = [ "dimension-nether" ]
		chance = "75"

	[songs.nether7_ballad_of_the_cats]
		triggers = [ "dimension-nether" ]
		chance = "75"

	[songs.end_amb1_mango]
		triggers = [ "dimension-end" ]
		chance = "150"

	[songs.end_amb2_serena]
		triggers = [ "dimension-end" ]
		chance = "150"

	[songs.end_amb3_signals]
		triggers = [ "dimension-end" ]
		chance = "150"

	[songs.end1_ender_waltz]
		triggers = [ "dimension-end" ]
		chance = "75"

	[songs.end2_last_way]
		triggers = [ "dimension-end" ]
		chance = "75"

	[songs.end3_search_in_purple]
		triggers = [ "dimension-end" ]
		chance = "75"

	[songs.end4_wonder]
		triggers = [ "dimension-end" ]
		chance = "75"

	[songs.end5_haggstrom]
		triggers = [ "dimension-end" ]
		chance = "75"

	[songs.end6_cassette]
		triggers = [ "dimension-end" ]
		chance = "75"

	[songs.menu1_lezends]
		triggers = [ "menu" ]

	[songs.menu4_moog_city]
		triggers = [ "menu" ]

	[songs.menu5_mutation]
		triggers = [ "menu" ]

	[songs.menu6_aerie]
		triggers = [ "menu" ]

